spring:
  config:
    import: "optional:configserver:"
  application:
    name: accounts
  profiles:
    active: production
management:
  endpoints:
    web:
      exposure:
        include: '*'
application:
  allow-get-accounts: ${accounts.allow-get-accounts}
eureka:
  client: ${eureka-client}
# ACTUATOR INFO
info:
  app:
    name: "Accounts"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}
